version: "3.7"

##
# CICEE v1.1.0 environment
#   Core CI environment definition
##

services:

  ci-generate-nuget-config:
    image: "${PROJECT_NAME}-ci:${PROJECT_VERSION_DOTNET}"
    build:
      context: ci
      dockerfile: Dockerfile
    command: ci/lib/generate-nuget-config-github.sh /root/.nuget/NuGet
    working_dir: /code
    volumes:
      - type: bind
        source: .
        target: /code
      - type: volume
        source: nugetconfig
        target: /root/.nuget/NuGet
    environment:
      # Environment variables with only a key are resolved to their values on the machine running (Docker) Compose.
      GITHUB_OWNER:
      GITHUB_AUTH_TOKEN:

  ci-exec:
    image: "${PROJECT_NAME}-ci:${PROJECT_VERSION_DOTNET}"
    build:
      context: ci
      dockerfile: Dockerfile
    command: "${CI_EXEC_CMD}"
    working_dir: /code
    volumes:
      # Project Code
      - type: bind
        source: .
        target: /code
      # Docker
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      # NPM configuration
      - type: volume
        source: npmconfig
        target: /root/.npmrc
      # NuGet configuration
      - type: volume
        source: nugetconfig
        target: /root/.nuget/NuGet
      # NuGet caches
      - type: volume
        source: nugetpackages
        target: /root/.nuget/packages
      - type: volume
        source: nugetsourcecache
        target: /root/.local/share/NuGet
      # Short syntax mount ( [SOURCE:]TARGET[:MODE] ) creates host directory if it does not exist
      # https://docs.docker.com/compose/compose-file/compose-file-v3/#long-syntax-3
      # AWS CLI configuration
      -  "${HOME}/.aws:/root/.aws"
    environment:
      # Environment variables with only a key are resolved to their values on the machine running (Docker) Compose.
      AWS_ACCESS_KEY_ID:
      AWS_ACCOUNT:
      AWS_REGION:
      AWS_SECRET_ACCESS_KEY:
      DOCKER_IMAGE_REPOSITORY:
      DRY_RUN:
      GITHUB_AUTH_TOKEN:
      GITHUB_OWNER:
      RELEASE_ENVIRONMENT:

volumes:
  npmconfig:
  nugetconfig:
  nugetpackages:
  nugetsourcecache:
