##
# Project-specific CI environment extensions
##

services:
  # cicee execution service.
  ci-exec:
    # depends_on:
    #   - pg
    environment:
      # Environment variables with only a key are resolved to their values on the machine running (Docker) Compose.
      #--
      # Project
      #--
      NUGET_API_KEY:
      NUGET_SOURCE:
    volumes:      
      # Hide host build results
      - type: volume
        target: /code/src/bin
      - type: volume
        target: /code/src/obj
      - type: volume
        target: /code/tests/integration/bin
      - type: volume
        target: /code/tests/integration/obj
      - type: volume
        target: /code/tests/unit/bin
      - type: volume
        target: /code/tests/unit/obj
    # NOTE: Root user specified below helps address permissions errors when using the default CICEE Dockerfile.
    user: root
